---
# tasks file for roles/nginx
- name: Install nginx
  yum:
    name: nginx
    state: present
  tags: nginx

- name: Remove default nginx site config
  file:
    path: /etc/nginx/conf.d/default.conf
    state: absent
  tags: nginx

- name: Deploy main nginx config
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf 
    owner: root
    mode: '0644'
  notify: Reload Nginx
  tags: nginx

- name: Deploy reverse proxy
  template:
    src: app-proxy.conf.j2
    dest: /etc/nginx/conf.d/{{ project_name }}.conf
  tags: nginx

- name: Fix nginx user for Amazon Linux
  become: yes
  replace:
    path: /etc/nginx/nginx.conf
    regexp: '^user\s+www-data;'
    replace: 'user nginx;'

- name: Test nginx configuration
  command: nginx -t
  changed_when: false
  notify: Reload Nginx
  tags: nginx

- name: Start and enable nginx
  service:
    name: nginx
    state: started
    enabled: true
  tags: nginx
